export const homeURL = "https://localhost:3000/";
export const apiURL = "https://localhost:3000/api/";
export const siteTitle = "CoBuy";
export const rootRoute = "/";
export const registerRoute = '/register';
export const loginRoute ="/login";
export const forgotPasswordRoute = '/forgotPassword';
export const notfoundRoute = '/404';
export const siteTheme = { primary: '#093170', secondary: '#ff9800' };